### PR TITLE
Refactor code directory structure

### PR DESCRIPTION
**Pull request by mattmoreira**
Moved typescript code from `codemod/output` to `src`, and rearranged the files into `src`

New directory structure:

image

### CODE REVIEW

**Comment by mattmoreira** [comment]
@jakubzitny, @TheWiseNoob and @mtltechtemp, this is the PR I've mentioned, can you please review it?

**Review by mtltechtemp — APPROVED** [review]
Looks great for me!

**Comment by jakubzitny** [comment]
I like it.. looks good, but let me try to test it a bit ;)

**Comment by mattmoreira** [comment]
@jakubzitny, were you able to test it?

**Review by jakubzitny — APPROVED** [review]
Looks good, sorry for delays. I'm quite overloaded with a lot of different work. Let's merge it and maybe update the upstream PR? Any maybe release beta version so more people can test it as well?

Do you guys use this in a production system somewhere as well?

**Comment by mattmoreira** [comment]
No worries @jakubzitny! I don't use it in a production system, however, I used to use in my last company, I can ask them to test it and see how it goes.

**Comment by jakubzitny** [comment]
> No worries @jakubzitny! I don't use it in a production system, however, I used to use in my last company, I can ask them to test it and see how it goes.

That would be awesome, I'll release the upstream PR as a beta version and if your ex-colleagues can test it, that would be awesome. The thing is that I still don't have the access to `evaporate` on NPM. So I'll create a new package and share it here 😉

**Pull request merged**
